- alias: Dempet lys
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {"state": "group off", "entity_id": "switch.nexa_remote"}
  action:
    - service: scene.turn_on
      entity_id: scene.dempet_lys