- alias: Bevegelse
  trigger:
    - platform: state
      entity_id: binary_sensor.everspring_sp103_pir_motion_sensor_sensor_9_0
      from: 'off'
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.garasje_paa

- alias: Ingen bevegelse
  trigger:
    - platform: state
      entity_id: binary_sensor.everspring_sp103_pir_motion_sensor_sensor_9_0
      from: 'on'
      to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.garasje_av

- alias: Alarm
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm_1
      from: 'disarmed'
      to: 'armed_home'
  action:
    - service: scene.turn_on
      entity_id: scene.alt_av