- alias: Pause
  trigger:
    - platform: state
      entity_id:  lock.hoveddr
      to: 'locked'
  action:
      service: remote.send_command
      data_template:
        entity_id: remote.stue
        command: Pause
        device: 32445691

- alias: Play
  trigger:
    - platform: state
      entity_id:  lock.hoveddr
      to: 'unlocked'
  action:
      service: remote.send_command
      data_template:
        entity_id: remote.stue 
        command: Play
        device: 32445691

- alias: Bevegelse registrert
  trigger:
    - platform: state
      entity_id:  binary_sensor.everspring_sp103_pir_motion_sensor_sensor_9_0
      to: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.garasje_lys

- alias: Ingen bevegelse
  trigger:
    - platform: state
      entity_id:  binary_sensor.everspring_sp103_pir_motion_sensor_sensor_9_0
      to: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.garasje_av