- alias: Movement
  trigger:
    - platform: state
      entity_id: binary_sensor.everspring_sp103_pir_motion_sensor_sensor_9_0
      from: 'off'
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.garasje_on

- alias: Movement ended
  trigger:
    - platform: state
      entity_id: binary_sensor.everspring_sp103_pir_motion_sensor_sensor_9_0
      from: 'on'
      to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.garasje_off

- alias: Alarm
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm_1
      from: 'disarmed'
      to: 'armed_home'
  action:
    - service: scene.turn_on
      entity_id: scene.all_off

- alias: God morgen
  trigger:
    - platform: sun
      event: sunrise
      offset: '00:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.stue_all_on

- alias: Demp lys kveld
  trigger:
    - platform: sun
      event: sunset
      offset: '+01:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.stue_evening