- alias: Bevegelse
  trigger:
    - platform: state
      entity_id: binary_sensor.everspring_sp103_pir_motion_sensor_sensor_9_0
      from: 'off'
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.garasje_lys

- alias: Bevegelse slutt
  trigger:
    - platform: state
      entity_id: binary_sensor.everspring_sp103_pir_motion_sensor_sensor_9_0
      from: 'on'
      to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.garasje_av

- alias: Alarm pa
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm_1
      from: 'disarmed'
      to: 'armed_home'
  action:
    - service: scene.turn_on
      entity_id: scene.alle_av

- alias: Alarm av
  initial_state: True
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm_1
      to: 'disarmed'
  action:
    - service: scene.turn_on
      entity_id: scene.alle_lys

- alias: Startup
  trigger:
    - platform: event
      event_type: homeassistant_start
  action:
    - service: notify.push
      data:
        message: HASS startet

- alias: Bevegelse loft
  trigger:
    - platform: state
      entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor_15_0
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.loft_full
  
- alias: Bevegelse loft
  trigger:
    - platform: state
      entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor_15_0
      to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.loft_av

- alias: Bevegelse kjeller
  trigger:
    - platform: state
      entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor_16_0
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.kjeller_full
  
- alias: Bevegelse kjeller
  trigger:
    - platform: state
      entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor_16_0
      to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.kjeller_av