- alias: Dempet lys
  trigger:
    - platform: state
      entity_id:  lock.hoveddr
      to: 'locked'
  action:
    - service: scene.turn_on
      entity_id: scene.fullt_lys


- alias: Harmony Pause contextual for activity
  trigger:
    - platform: state
      entity_id:  lock.hoveddr
      to: 'locked'
  action:
      service: remote.send_command
      data_template:
        entity_id: remote.stue 
        command: Pause
        device: >
          {% if is_state("remote.stue", "Watch TV") %}
            30979559
          {% elif is_state("remote.stue", "Watch Apple TV 2") %}
            32445691
          {% elif is_state("remote.stue", "Watch Apple TV") %}
            32445691            
          {% endif %}