- alias: Bevegelse
  
  trigger:
    - platform: state
      entity_id:  binary_sensor.everspring_sp103_pir_motion_sensor_sensor_9_0
      from: 'off'
      to: 'on'

  action:
    service: homeassistant.turn_off
    entity_id:
      - light.tradfri_bulb_e27_opal_1000lm
      - light.tradfri_bulb_e27_opal_1000lm_2
      - light.tradfri_bulb_e27_opal_1000lm_3

  data:
      brightness: 254

- alias: Ingen-bevegelse

  trigger:
    - platform: state
      entity_id:  binary_sensor.everspring_sp103_pir_motion_sensor_sensor_9_0
      from: 'on'
      to: 'off'

  action:
    service: homeassistant.turn_off
    entity_id:
      - light.tradfri_bulb_e27_opal_1000lm
      - light.tradfri_bulb_e27_opal_1000lm_2
      - light.tradfri_bulb_e27_opal_1000lm_3

  data:
      brightness: 0