- alias: Bevegelse
  trigger:
    - platform: state
      entity_id: binary_sensor.everspring_sp103_pir_motion_sensor_sensor_9_0
      from: 'off'
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.garasje_lys

- alias: Bevegelse slutt
  trigger:
    - platform: state
      entity_id: binary_sensor.everspring_sp103_pir_motion_sensor_sensor_9_0
      from: 'on'
      to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.garasje_av

- alias: Alarm pa
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm_1
      from: 'disarmed'
      to: 'armed_home'
  action:
    - service: scene.turn_on
      entity_id: scene.alle_av

- alias: Alarm av
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm_1
      to: 'disarmed'
  action:
    - service: scene.turn_on
      entity_id: scene.alle_lys

- alias: God morgen
  trigger:
    - platform: time
      after: '06:50'
  action:
    - service: scene.turn_on
      entity_id: scene.stue_lys

- alias: Demp lys
  trigger:
    - platform: time
      after: '19:30'
  action:
    - service: scene.turn_on
      entity_id: scene.stue_kveld

- alias: Sen kveld
  trigger:
    - platform: time
      after: '22:00'
  action:
    - service: scene.turn_on
      entity_id: scene.stue_film

- alias: Soverom
  trigger:
    - platform: time
      after: '21:00'
  action:
    - service: scene.turn_on
      entity_id: scene.soverom_kveld

- alias: Startup
  trigger:
    - platform: event
      event_type: homeassistant_start
  action:
    - service: notify.push
      data: HASS Started