homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  #latitude: 63.4167
  #longitude: 10.4167
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  #Tilpasse
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables ios
ios:

# Enables configuration UI
config:

cloud:
  alexa:
    filter:
      include_entities:
        - light.fibaro_system_fgd212_dimmer_2_level_11_0
      include_domains:
        - switch
    entity_config:
      light.fibaro_system_fgd212_dimmer_2_level_11_0:
        name: Living Room
        description: Living Room Downlights

  google_actions:
    filter:
      include_entities:
        - light.fibaro_system_fgd212_dimmer_2_level_9
        - light.fibaro_system_fgd212_dimmer_2_level_7
        - light.fibaro_system_fgd212_dimmer_2_level_3
        - light.fibaro_system_fgd212_dimmer_2_level_5
        - light.fibaro_system_fgd212_dimmer_2_level_11
        - light.fibaro_system_fgd212_dimmer_2_level_13
        - switch.fibaro_system_fgwpef_wall_plug_gen5_switch
        - scene.stue_film
        - scene.stue_lys
        - scene.stue_kveld
    entity_config:
      light.fibaro_system_fgd212_dimmer_2_level_7:
        name: Downlights
        room: Stue
      light.fibaro_system_fgd212_dimmer_2_level_3:
        name: Hovedlampe
        room: Stue
      light.fibaro_system_fgd212_dimmer_2_level_5:
        name: Spisebord
        room: Stue
      light.fibaro_system_fgd212_dimmer_2_level_9:
        name: Kjokken
        room: Stue
      light.fibaro_system_fgd212_dimmer_2_level_11:
        name: Gang
        room: Stue
      light.fibaro_system_fgd212_dimmer_2_level_13:
        name: Kjellergang
        room: Kjeller
      switch.fibaro_system_fgwpef_wall_plug_gen5_switch:
        name: Kjokkenhylle
        room: Stue
      scene.stue_film:
        name: film
        room: Stue
      scene.stue_lys:
        name: fullt lys
        room: Stue
      scene.stue_kveld:
        name: kveldslys
        room: Stue                

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  #trusted_networks:
  # - 127.0.0.1
  # - 192.168.0.0/24
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Includes
scene: !include_dir_list scenes/
automation: !include automations.yaml
group: !include groups.yaml
# switch: !include switches.yaml

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

# Z-Wave dongle
zwave:
  usb_path: /dev/ttyACM0
  debug: True

# IKEA
# tradfri:
#  host: 192.168.86.32
#  api_key: !secret ikea_key

ifttt:
  key: !secret ifttt_key

notify:
  - name: push
    platform: pushbullet
    api_key: !secret pushbullet_key

# Verisure
verisure:
  username: !secret verisure_username
  password: !secret verisure_password
  code_digits: 6

# Media
media_player:
  - platform: spotify
    client_id: !secret spotify_id
    client_secret: !secret spotify_secret
  - platform: braviatv
    host: 192.168.86.230
    name: TV - kjellerstue
  - platform: samsungtv    
    name: TV - stue
    host: 192.168.86.29
    mac: 0c:89:10:ce:be:b4

# Remotes
remote:
  - platform: harmony
    name: Stue
    activity: Watch Apple TV

#emulated_hue:
#  host_ip: 192.168.86.244
#  listen_port: 8300
#  off_maps_to_on_domains:
#    - script
#    - scene
#  expose_by_default: false
