homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  #latitude: 63.4167
  #longitude: 10.4167
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  #Tilpasse
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Includes
scene: !include_dir_list scenes/
automation: !include automation.yaml
group: !include groups.yaml
# switch: !include switches.yaml

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

# Z-Wave dongle
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/lib/python3.4/site-packages/python_openzwave/ozw_config
  debug: True

# Verisure
verisure:
  username: !secret verisure_username
  password: !secret verisure_password
  code_digits: 6

# Media
media_player:
  - platform: spotify
    client_id: !secret spotify_id
    client_secret: !secret spotify_secret
  - platform: braviatv
    host: 192.168.86.230
    name: TV - kjellerstue
  - platform: samsungtv    
    name: TV - stue
    host: 192.168.86.29
    mac: 0c:89:10:ce:be:b4
  - platform: cast

# Remotes
remote:
  - platform: harmony
    name: Loftet
    host: 192.168.86.71
  - platform: harmony
    name: Stue
    host: 192.168.86.31

tradfri:
  host: 192.168.86.238
  api_key: !secret tradfri_api