- platform: template
    switches:
      tv:
        value_template: "{% if is_state('remote.stue', 'on') %}on{% else %}off{% endif %}"
        turn_on:
          service: remote.turn_on
          entity_id: remote.stue
        turn_off:
          service: remote.turn_off
          entity_id: remote.stue